import{S as h,i as l}from"./assets/vendor-6a4ae241.js";(function(){const t=document.createElement("link").relList;if(t&&t.supports&&t.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))s(e);new MutationObserver(e=>{for(const o of e)if(o.type==="childList")for(const a of o.addedNodes)a.tagName==="LINK"&&a.rel==="modulepreload"&&s(a)}).observe(document,{childList:!0,subtree:!0});function r(e){const o={};return e.integrity&&(o.integrity=e.integrity),e.referrerpolicy&&(o.referrerPolicy=e.referrerpolicy),e.crossorigin==="use-credentials"?o.credentials="include":e.crossorigin==="anonymous"?o.credentials="omit":o.credentials="same-origin",o}function s(e){if(e.ep)return;e.ep=!0;const o=r(e);fetch(e.href,o)}})();const d="live_aLXJAm9hp9NZ1c9OwWR66Hw3VSH9ecgndIbTnT3SC8CgHMrvia7gIY31FZbfVDqM";function m(){const n="https://api.thecatapi.com/v1/breeds",t=new URLSearchParams({api_key:d});return fetch(`${n}?${t}`).then(r=>{if(!r.ok)throw new Error(r.status);return r.json()})}function p(n){const t="https://api.thecatapi.com/v1/images/search",r=new URLSearchParams({breed_ids:n,api_key:d});return fetch(`${t}?${r}`).then(s=>{if(!s.ok)throw new Error(s.status);return s.json()})}const c={select:document.querySelector(".breed-select"),loader:document.querySelector(".loader"),error:document.querySelector(".error")};function u(){c.loader.classList.remove("is-hidden")}function f(){c.loader.classList.add("is-hidden")}function g(){c.select.classList.add("is-hidden")}function y(){c.select.classList.remove("is-hidden")}const i={select:document.querySelector(".breed-select"),section:document.querySelector(".cat-info")};u();g();m().then(n=>{const t=L(n);i.select.innerHTML=t,new h({select:"select.breed-select"}),f(),y()}).catch(n=>l.error({title:"Oops!",message:"Something went wrong! Try reloading the page!",position:"topRight"}));function L(n){return n.map(({id:t,name:r})=>`<option value="${t}" class="single-option">${r}</option>`).join("")}function S(n){const{url:t,breeds:[{name:r,description:s,temperament:e}]}=n[0];return`<img class="js-image" src="${t}" alt="${r}"/>
  <ul class="js-list">
    <li class="js-item">
      <h1 class="js-title">${r}</h1>
      <p class="js-description">${s}</p>
      <p class="js-temperament">Temperament: ${e}</p>
    </li>
  </ul>`}i.select.addEventListener("change",w);function w(n){i.section.innerHTML="",u();const t=n.target.value;p(t).then(r=>{i.section.insertAdjacentHTML("afterbegin",S(r))}).catch(r=>l.error({title:"Oops!",message:"Something went wrong! Try reloading the page!",position:"topRight"})).finally(()=>{f()})}
//# sourceMappingURL=commonHelpers.js.map
